### ISSUE TITLE
Expose escaping/unescaping html as an option/utility

### ISSUE THREAD

**Issue by wheresrhys** [chjj/marked#764] opened 2016-06-28 21:36 UTC
I'm using markdown as the authoring syntax for a cli tool - I'm able to hook in to the renderer to replace html tags with calls to chalk.

The one place I'm not able to decouple markdown from html is escaped characters being converted into html entities. Would you accept a PR to enable turning off html escaping via an option?

**Comment by adam-lynch** [comment] 2016-07-03 00:13
Duplicate of #529

**Comment by mharward** [comment] 2016-07-03 21:34
This would be excellent and a problem we have also run into (in a slightly different context).

**Comment by amasad** [comment] 2017-01-08 22:55
I've worked around this by using lodash's unescape

```
const renderer = new marked.Renderer();

// Pass html unescaped
renderer.html = str => _.unescape(str);
```

**Comment by joshbruce** [comment] 2017-12-25 20:35
#985

**Closed by joshbruce** 2017-12-25 20:35 UTC
