### ISSUE TITLE
Errors trying to convert mapnik wiki

### ISSUE THREAD

**Issue by TeAmigo** [chjj/marked#1044] opened 2018-02-02 20:29 UTC
## Expectation

the markdown, downloaded from https://github.com/mapnik/mapnik/wiki

## Result
Unhandled rejection Error: Unknown language: "csv"
Please report this to https://github.com/chjj/marked.
    at Object.highlight (/usr/local/lib/node_modules/github-wikito-converter/node_modules/highlight.js/lib/highlight.js:443:13)
    at Renderer.mainRenderer.code (/usr/local/lib/node_modules/github-wikito-converter/dist/markdown.js:34:79)
    at Parser.tok (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:999:28)
    at Parser.parse (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:944:17)
    at Function.Parser.parse (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:931:17)
    at marked (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:1252:19)
    at Markdown.convertMarkdownString (/usr/local/lib/node_modules/github-wikito-converter/dist/markdown.js:109:14)
    at Markdown.convertMarkdownFile (/usr/local/lib/node_modules/github-wikito-converter/dist/markdown.js:116:19)
    at WikiConverter.<anonymous> (/usr/local/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:87:41)
    at Array.forEach (native)
    at WikiConverter.computePages (/usr/local/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:83:27)
    at WikiConverter.getPages (/usr/local/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:96:14)
    at HtmlWriter.write (/usr/local/lib/node_modules/github-wikito-converter/dist/html-writer.js:33:34)
    at WikiConverter.<anonymous> (/usr/local/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:60:43)
    at tryCatcher (/usr/local/lib/node_modules/github-wikito-converter/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/github-wikito-converter/node_modules/bluebird/js/main/promise.js:510:31)

## What was attempted

gwtc ../mapnik.wiki/

**Comment by joshbruce** [comment] 2018-02-02 20:39
Can you be more specific on what you was done here? When I go to the wiki I don't know what was downloaded. Also, not sure what `gwtc ../mapnik.wiki/` does as it relates to Marked.

It appears a `.md` file or string was not passed in - instead a `.csv` file or string was passed in; Marked doesn't parse CSV files; so, that would not be a problem with Marked.

**Comment by Feder1co5oave** [comment] 2018-02-08 19:40
> ## Expectation
> the markdown, downloaded from https://github.com/mapnik/mapnik/wiki

I'm guessing you meant https://github.com/mapnik/mapnik/wiki/CSV-Plugin

> ## Result
>
> Unhandled rejection Error: Unknown language: "csv"
Please report this to https://github.com/chjj/marked.
at Object.highlight (/usr/local/lib/node_modules/github-wikito-converter/node_modules/**highlight.js/lib/highlight.js:443:13**)
at Renderer.mainRenderer.code (/usr/local/lib/node_modules/**github-wikito-converter/dist/markdown.js:34:79**)
at Parser.tok (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:999:28)
at Parser.parse (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:944:17)
at Function.Parser.parse (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:931:17)
at marked (/usr/local/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:1252:19)
...

As you can see from the bold part, the error was raised inside the `highlight.js` file, being called from the `markdown.js` file of the `github-wikito-converter` module. This is not caused by marked.
What happened is that inside the `github-wikito-converter` module a new `code` renderer was written, and it uses `highlight.js` to do syntax formatting of code. Whenever a language unknown to highlight.js is 
given, it raises an exception. In this case, `csv`.

**Comment by joshbruce** [comment] 2018-02-09 04:18
Closing based on further clarification from @Feder1co5oave. @TeAmigo, if you believe this is not a valid assessment, please let us know, and I can reopen it.

**Closed by joshbruce** 2018-02-09 04:18 UTC
