### ISSUE TITLE
Blockquotes not recognized

### ISSUE THREAD

**Issue by Kasperfred** [chjj/marked#874] opened 2017-03-18 14:14 UTC
I'm having an issue where blockquotes aren't rendered using  marked. 

By considering the following:

    > This is a blockquote 

It's expected to be rendered as:

> This is a blockquote 

However, it's rendered as plain text with the following HTML:

    <p>This is a blockquote</p>

The issue seems to lie in the regular expression: `/^( *>[^\n]+(\n(?!def)[^\n]+)*\n*)+/`, found in the `marked.js` file, which doesn't match the line above. 

A proposed solution is to edit the regular expression to be: `/( *>[^\n]+(\n(?!def)[^\n]+)*\n*)+/` which would appear to solve the problem with only one caveat that if the "empty" line after the blockquote contains whitespace it will continue to match the proceding paragraphs as illustrated below.

<img width="369" alt="screen shot 2017-03-18 at 3 07 47 pm" src="https://cloud.githubusercontent.com/assets/13367236/24072787/be7aee06-0bec-11e7-8961-34287d7f74dd.png">

Also, I'm unsure if the proposed solution will break other parts of the codebase which is why I'm hesitant to open it as a pull request. 

If somebody does have insight into this issue, and is able to point out flaws in the reasoning above it would be greatly appreciated.

**Comment by broskoski** [comment] 2017-03-20 17:34
+ Same issue here.

**Comment by cnderrauber** [comment] 2017-06-06 05:18
i get same problem

**Comment by manuel-di-iorio** [comment] 2017-09-17 18:26
👍

**Comment by leoyli** [comment] 2017-10-27 04:32
I also have the same issue...

**Comment by leoyli** [comment] 2017-10-27 14:56
This issue should be closed.  Since that's the issue is from the user not the lib itself.

Check the data string first to see if it `>` rather than `/&gt;`.  If your input is from server, it is possible to get `/&gt;+` instead.  In that case, just replace your string using `.replace(/&gt;+/g, '>')` before put it into `marked()`.

**Comment by umeshk149** [comment] 2017-11-14 15:21
This works for me. `sanitize` can be `true` or `false`

```javascript
(function markdownToHtml() {
	var el = document.querySelectorAll(".markdown");
	for(var i = 0; i<el.length; i++ ){
		el[i].innerHTML = marked(el[i].innerHTML.replace(/&gt;+/g, '>'), { sanitize: true });
	}
})();
```

**Comment by Feder1co5oave** [comment] 2017-12-27 03:09
```bash
$ bin/marked
> This is a blockquote
^D
<blockquote>
<p>This is a blockquote </p>
</blockquote>
```

Definitely a user issue.
@joshbruce this can be closed

**Comment by joshbruce** [comment] 2017-12-27 12:35
Consensus seems to be this is not an issue with Marked. Closing.

**Closed by joshbruce** 2017-12-27 12:35 UTC

**Comment by jabiertxof** [comment] 2019-01-28 14:33
Im sure I only have "> " and still have problems

**Comment by UziTech** [comment] 2019-01-28 14:57
@jabiertxof Can you share a link to a [demo](https://marked.js.org/demo/) with the markdown that causes your issue?

**Comment by jabiertxof** [comment] 2019-01-28 15:04
Forget me I'm getting code to parse from innerHTML and is converted to entities. Sorry for the noise and thanks for the fast reply.

**Comment by messizqin** [comment] 2021-11-24 14:14
My `> This is a block quote` is the first sentence in a `div`, which somehow indented by **4 spaces or 1 tab**, thus identified as code block. the solution is simply `el.innerHTML = marked(el.innerHTML.trim())`
