### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Forward2015** [chjj/marked#955] opened 2017-11-23 07:43 UTC
Please see here : [https://booolen.com](https://booolen.com/p/72) and open your browser F12 and you will see the follwing error.  How to fix it?

vendor.bb27c102dd9bc41a3e87.js:6 TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.
    at e.lex (2.337a923ed8ad389ae3f0.js:1)
    at Function.e.lex (2.337a923ed8ad389ae3f0.js:1)
    at h (2.337a923ed8ad389ae3f0.js:1)
    at o.formatMd (2.337a923ed8ad389ae3f0.js:1)
    at Fa.get (vendor.bb27c102dd9bc41a3e87.js:6)
    at Fa.evaluate (vendor.bb27c102dd9bc41a3e87.js:6)
    at o.formatMd (vendor.bb27c102dd9bc41a3e87.js:6)
    at o.render (2.337a923ed8ad389ae3f0.js:1)
    at o.e._render (vendor.bb27c102dd9bc41a3e87.js:6)
    at o.r (vendor.bb27c102dd9bc41a3e87.js:6)

**Comment by flamusdiu** [comment] 2017-12-03 13:57
@Forward2015 I have noticed similar message with `src.replace` and usually it's caused by reading a var being assigning it. I wish, however, these give more debug information then what appears to be generic JS error messages. I would probably look at your logic and make sure you are not unintentionally trying to parse a var that happens to be undefined.

**Closed** 2018-01-20 22:16 UTC
Labels: L2 - annoying, help wanted
