### ISSUE TITLE
How can I extend this

### ISSUE THREAD

**Issue by erickskrauch** [chjj/marked#292] opened 2013-11-21 15:46 UTC
I have this regexp

```
'v[https://www.youtube.com/watch?v=123]'.replace(/v\[(https?:\/\/(www.)?youtube.com\/watch\?v=[^\]]+)\]/,'<iframe width="560" height="315" src="$1" frameborder="0" allowfullscreen></iframe>' )
```

Should get a tag v[url_youtube_video]. How can I expand your plugin to this?

**Comment by joshbruce** [comment] 2017-12-22 00:13
Closing as duplicate of closed issue.

**Closed by joshbruce** 2017-12-22 00:13 UTC
