### ISSUE TITLE
BUMP: Extending Custom Elements

### ISSUE THREAD

**Issue by DerekTBrown** [chjj/marked#928] opened 2017-08-26 21:17 UTC
There needs to be a way of adding custom elements.  A lot of people are asking about it:

https://github.com/chjj/marked/issues/865 
https://github.com/chjj/marked/pull/821
https://github.com/chjj/marked/issues/60
https://github.com/chjj/marked/issues/57
https://github.com/chjj/marked/pull/35

**Comment by DerekTBrown** [comment] 2017-08-26 21:23
@chjj doesn't look like anyone is maintaining this project.  Are you looking for someone to help out?

**Comment by matt-** [comment] 2017-08-29 00:59
Dupe of #865
#821
#60
#57
#35

**Closed by matt-** 2017-08-29 00:59 UTC
