### ISSUE TITLE
Support emoji's like in Github Markdown

### ISSUE THREAD

**Issue by Bartvds** [chjj/marked#233] opened 2013-08-16 16:02 UTC
:octocat: The markdown parser used by Github supports [emoji](http://www.emoji-cheat-sheet.com/)s.

:interrobang: It'd be nice if they would be enabled in `marked` so they show up correctly in dependant projects like npm's readme pages, as they currently display as unparsed codes.

:point_right: https://github.com/isaacs/npm-www/issues/392 :point_left:

The :warning: and :x: are great for emphasis.

**Comment by johanbrook** [comment] 2015-05-11 17:32
Any news on this? Would be great if this can be merged, if possible!

**Comment by ilianiv** [comment] 2016-09-15 10:06
3 years later issue is still opened... Will `marked` support emojis or it won't?

**Comment by antonreshetov** [comment] 2017-08-22 07:31
Also needed a similar functionality.
I wrote simple parsser, maybe it will help someone. 😉

```js
// parser.js
import marked from 'marked'
import emoji from 'node-emoji'

export function parse = (markdown) => {
  const replacer = (match) => emoji.emojify(match)
  markdown = markdown.replace(/(:.*:)/g, replacer)
	 
  return marked(markdown)
}
```

```js
// use
import { parse } from './parse'

parser(':muscle: of emoji') // 💪 of emoji
```

**Comment by Bartvds** [comment] 2017-08-22 08:39
@antonreshetov You'll probably want test your function with more complex input, like multiple emoji's and regular :'s mixed together in various combinations.

**Comment by antonreshetov** [comment] 2017-08-22 08:44
@Bartvds  it's just a blank, my problems are solved. If someone needs to add different combinations of regression, just describe them as needed. 😉

**Comment by joshbruce** [comment] 2017-12-06 01:22
See #956 

Closing as stale.

Right now the focus is on two Markdown specifications to pursue solid support for:

GFM and CommonMark: The GFM support appears to be an extension, not part of the core, and I haven't delved far enough into CommonMark to know if it's part of that spec. Therefore, in answer to the question of whether it will be supported...not right now. But, let's see what the future brings.

**Closed by joshbruce** 2017-12-06 01:22 UTC

**Comment by Bartvds** [comment] 2017-12-06 08:51
It's fine, we're using unicode emoji's these days 👈😎👉

**Comment by AhmedBHameed** [comment] 2022-06-29 21:09
@antonreshetov 

Thank you for the nice function. However, I just enhance the functionality since it was producing an issue with the following

`:information_source: [scripting language](https://en.wikipedia.org/wiki/Scripting_language)`

The output was ℹ️[scripting language](https

Also prevent ruinding the code snippet.

```js
const parseEmojis = (markdown: string) => {
  const emojify = (match: string) => {
    console.log(emoji.emojify(match));
    return `<span className="emoji">${emoji.emojify(match)}</span>`;
  };

  markdown = markdown.replace(
      /<(pre|template|code)[^>]*?>[\s\S]+?<\/(pre|template|code)>/g,
      function (m) {
        return m.replace(/:/g, '__colon__');
      }
    )
    .replace(/:(\w+?):/gi, emojify)
    .replace(/__colon__/g, ':');

  return markdown;
};
```

**Comment by UziTech** [comment] 2022-07-03 21:58
You could also create a [custom extension](https://marked.js.org/using_pro#extensions) to render markdown differently.

```js
const emoji = {
  name: 'emoji',
  level: 'inline',                          // This is an inline-level tokenizer
  start(src) { return src.indexOf(':'); }, // Hint to Marked.js to stop and check for a match
  tokenizer(src, tokens) {
    const rule = /^:(\w+):+/;           // Regex for the complete token, anchor to string start
    const match = rule.exec(src);
    if (match) {
      return {                               // Token to generate
        type: 'emoji',               // Should match "name" above
        raw: match[0],                       // Text to consume from the source
        emoji: match[1]                       // Additional custom properties
      };
    }
  },
  renderer(token) {
    return `<span className="emoji">${emoji.emojify(token.emoji)}</span>`;
  }
};

marked.use({extensions: [emoji]});
```

**Comment by UziTech** [comment] 2022-12-24 04:59
I created [marked-emoji](https://www.npmjs.com/package/marked-emoji) so people can easily install it.
